'use strict';
/**
 * compiler/to-mcpuse.js
 *
 * Converts an AgentDOM manifest (.well-known/agentdom.json) into a
 * fully working mcp-use server scaffold — both TypeScript and Python.
 *
 * The generated server:
 *   • Exposes every AgentDOM capability as an mcp-use tool
 *   • Dispatches via AgentDOM's HTTP API (api.getagentdom.com or local)
 *   • Includes the mcp-use Inspector at http://localhost:<port>/inspector
 *   • Supports auth (api_key / oauth2) via env vars
 *
 * Usage (from publisher CLI):
 *   agentdom-publisher mcpuse --host=github.com --out=./my-github-server
 *   agentdom-publisher mcpuse --manifest=.well-known/agentdom.json --lang=python
 */

const fs   = require('fs');
const path = require('path');

// Sanitise any string into a valid tool name
function slugify(raw, operationId) {
  const base = (operationId && !String(raw).includes('[object'))
    ? operationId
    : String(raw);
  return base
    .replace(/\[object Object\]/g, '')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .slice(0, 64) || 'tool_unknown';
}

// ── TypeScript scaffold ────────────────────────────────────────────────────

function buildTsServer(manifest, opts = {}) {
  const { agentdomApi = 'http://localhost:3700', port = 3000 } = opts;
  const host   = manifest.host;
  const name   = manifest.name   || host;
  const desc   = manifest.description || `AgentDOM bridge for ${host}`;
  const auth   = manifest.auth   || { method: 'none' };
  const caps   = manifest.capabilities || [];

  // Build one tool block per capability
  const toolBlocks = caps.map(cap => {
    const args = cap.args || {};
    const props = Object.entries(args).map(([k, v]) => {
      const type = v.type === 'number' ? 'z.number()' : v.type === 'boolean' ? 'z.boolean()' : 'z.string()';
      const required = v.required !== false;
      const desc = v.description ? `.describe(${JSON.stringify(v.description)})` : '';
      return `    ${k}: ${type}${desc}${required ? '' : '.optional()'}`;
    }).join(',\n');

    const schemaBody = props ? `z.object({\n${props}\n  })` : 'z.object({})';
    const intentSlug = slugify(cap.intent, cap.operation_id);

    return `
  // ── ${cap.intent} ───────────────────────────────────────────
  server.tool({
    name: ${JSON.stringify(intentSlug)},
    description: ${JSON.stringify(cap.description || cap.intent)},
    schema: ${schemaBody},
  }, async (args) => {
    const result = await dispatch(${JSON.stringify(cap.intent)}, args);
    return text(JSON.stringify(result, null, 2));
  });`;
  }).join('\n');

  // Auth env var hint
  const authComment = auth.method === 'api_key'
    ? `// Auth: set ${host.toUpperCase().replace(/\./g, '_')}_API_KEY in your environment`
    : auth.method === 'oauth2' || auth.method === 'oauth2_pkce'
    ? `// Auth: set ${host.toUpperCase().replace(/\./g, '_')}_ACCESS_TOKEN in your environment`
    : '// Auth: none required';

  return `/**
 * AgentDOM × mcp-use bridge for ${name}
 * Generated by: agentdom-publisher mcpuse --host=${host}
 *
 * ${desc}
 *
 * Usage:
 *   npm install && npm start
 *   Inspector: http://localhost:${port}/inspector
 *   Connect to Claude: add this URL to your MCP client
 */

import { MCPServer, text } from 'mcp-use/server';
import { z } from 'zod';

${authComment}
const AGENTDOM_API = process.env.AGENTDOM_API_URL || ${JSON.stringify(agentdomApi)};
const AUTH_TOKEN   = process.env.${host.toUpperCase().replace(/\./g, '_')}_TOKEN || '';

// ── AgentDOM dispatcher ──────────────────────────────────────────────────────
async function dispatch(intent: string, args: Record<string, unknown>) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (AUTH_TOKEN) headers['Authorization'] = \`Bearer \${AUTH_TOKEN}\`;

  const res = await fetch(\`\${AGENTDOM_API}/api/agentdom/dispatch\`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ intent, host: ${JSON.stringify(host)}, args }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(\`AgentDOM dispatch failed [\${res.status}]: \${err}\`);
  }
  return res.json();
}

// ── MCP Server ───────────────────────────────────────────────────────────────
const server = new MCPServer({
  name: ${JSON.stringify(name + ' (AgentDOM)')},
  version: '1.0.0',
  description: ${JSON.stringify(desc)},
});
${toolBlocks}

// Start with built-in Inspector
await server.listen(${port});
// Inspector: http://localhost:${port}/inspector
`;
}

function buildTsPackageJson(manifest, port = 3000) {
  return JSON.stringify({
    name: `agentdom-${manifest.host.replace(/\./g, '-')}-mcp`,
    version: '1.0.0',
    description: `AgentDOM × mcp-use bridge for ${manifest.host}`,
    type: 'module',
    main: 'dist/server.js',
    scripts: {
      start: 'tsx server.ts',
      build: 'tsc',
      dev:   'tsx watch server.ts',
    },
    dependencies: {
      'mcp-use':  'latest',
      'zod':      '^3.0.0',
    },
    devDependencies: {
      'tsx':        '^4.0.0',
      'typescript': '^5.0.0',
    },
  }, null, 2);
}

// ── Python scaffold ────────────────────────────────────────────────────────

function buildPyServer(manifest, opts = {}) {
  const { agentdomApi = 'http://localhost:3700', port = 8000 } = opts;
  const host = manifest.host;
  const name = manifest.name || host;
  const desc = manifest.description || `AgentDOM bridge for ${host}`;
  const auth = manifest.auth || { method: 'none' };
  const caps = manifest.capabilities || [];

  const authComment = auth.method === 'api_key'
    ? `# Auth: set ${host.toUpperCase().replace(/\./g, '_')}_TOKEN in env`
    : auth.method.startsWith('oauth')
    ? `# Auth: set ${host.toUpperCase().replace(/\./g, '_')}_ACCESS_TOKEN in env`
    : '# Auth: none required';

  const toolDefs = caps.map(cap => {
    const args = cap.args || {};
    const params = Object.entries(args).map(([k, v]) => {
      const pyType = v.type === 'number' ? 'float' : v.type === 'boolean' ? 'bool' : 'str';
      const optional = v.required === false ? ' = None' : '';
      return `    ${k}: Annotated[${pyType}, Field(description=${JSON.stringify(v.description || k)})]${optional}`;
    }).join(',\n');

    const argDict = Object.keys(args).length
      ? `{${Object.keys(args).map(k => `"${k}": ${k}`).join(', ')}}`
      : '{}';

    const intentSlug = slugify(cap.intent, cap.operation_id);

    return `

@server.tool(
    name=${JSON.stringify(intentSlug)},
    description=${JSON.stringify(cap.description || cap.intent)},
)
async def ${intentSlug}(
${params || '    _: Annotated[str, Field(description="unused")] = ""'}
) -> str:
    result = await dispatch(${JSON.stringify(cap.intent)}, ${argDict})
    return json.dumps(result, indent=2)`;
  }).join('\n');

  return `"""
AgentDOM × mcp-use bridge for ${name}
Generated by: agentdom-publisher mcpuse --host=${host} --lang=python

${desc}

Usage:
    pip install mcp-use httpx
    python server.py
    Inspector: http://localhost:${port}/inspector
"""

import json
import os
from typing import Annotated
from pydantic import Field
from mcp_use import MCPServer
import httpx

${authComment}
AGENTDOM_API = os.environ.get("AGENTDOM_API_URL", ${JSON.stringify(agentdomApi)})
AUTH_TOKEN   = os.environ.get(${JSON.stringify(host.toUpperCase().replace(/\./g, '_') + '_TOKEN')}, "")


async def dispatch(intent: str, args: dict) -> dict:
    headers = {"Content-Type": "application/json"}
    if AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {AUTH_TOKEN}"
    async with httpx.AsyncClient() as client:
        res = await client.post(
            f"{AGENTDOM_API}/api/agentdom/dispatch",
            headers=headers,
            json={"intent": intent, "host": ${JSON.stringify(host)}, "args": args},
            timeout=30,
        )
        res.raise_for_status()
        return res.json()


server = MCPServer(name=${JSON.stringify(name + ' (AgentDOM)')}, version="1.0.0")
${toolDefs}


if __name__ == "__main__":
    server.run(transport="streamable-http", port=${port})
    # Inspector: http://localhost:${port}/inspector
`;
}

// ── Scaffold writer ────────────────────────────────────────────────────────

function scaffold(manifest, opts = {}) {
  const {
    outDir = process.cwd(),
    lang   = 'typescript',
    agentdomApi,
    port,
  } = opts;

  const dir = path.resolve(outDir);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  if (lang === 'python' || lang === 'py') {
    const server = buildPyServer(manifest, { agentdomApi, port });
    fs.writeFileSync(path.join(dir, 'server.py'), server);
    fs.writeFileSync(path.join(dir, 'requirements.txt'), 'mcp-use\nhttpx\n');
    return { files: ['server.py', 'requirements.txt'], dir };
  }

  // Default: TypeScript
  const server  = buildTsServer(manifest, { agentdomApi, port });
  const pkgJson = buildTsPackageJson(manifest, port);
  const tsConfig = JSON.stringify({
    compilerOptions: {
      target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
      outDir: 'dist', strict: true, esModuleInterop: true,
    },
  }, null, 2);

  fs.writeFileSync(path.join(dir, 'server.ts'),      server);
  fs.writeFileSync(path.join(dir, 'package.json'),   pkgJson);
  fs.writeFileSync(path.join(dir, 'tsconfig.json'),  tsConfig);
  fs.writeFileSync(path.join(dir, 'README.md'),
    `# ${manifest.name || manifest.host} — AgentDOM × mcp-use\n\n` +
    `Auto-generated MCP server bridge.\n\n` +
    `\`\`\`bash\nnpm install\nnpm start\n# Inspector: http://localhost:${port || 3000}/inspector\n\`\`\`\n`
  );

  return { files: ['server.ts', 'package.json', 'tsconfig.json', 'README.md'], dir };
}

module.exports = { buildTsServer, buildPyServer, scaffold };
